# docker-compose build
# docker-compose up -d
# http://localhost:21345
# にアクセスしてHello Worldが出れば正常動作

version: '3'

services:
  db-container:
    build:
      context: db
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "25432:5432"

  flask-container:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "21345:5000"
